/**
 * Copyright 2025-2026 jrobiche
 *
 * This file is part of libaustralis.
 *
 * libaustrais is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * libaustralis is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * libaustralis. If not, see <https://www.gnu.org/licenses/>.
 */
// TODO define tests
// TODO document functions
// TODO improve logging
// TODO improve error handling/bubbling
// TODO verify response codes
use crate::utils::GenericResult;
use log::{error, warn};
use serde;

pub const API_ROOT: &str = "https://catalog.xboxlive.com";

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LiveImage {
    pub media_type: usize,
    pub relationship_type: Option<usize>,
    pub format: usize,
    pub size: usize,
    pub file_url: String,
}

impl LiveImage {
    pub async fn file_bytes(&self) -> GenericResult<Vec<u8>> {
        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(60))
            .build()?;
        let req = client.get(&self.file_url);
        match req.send().await {
            Ok(resp) => match resp.bytes().await {
                Ok(x) => Ok(x.to_vec()),
                Err(err) => {
                    let msg = "Failed to get image bytes from response.";
                    error!("{} Got the following error: {}", msg, err);
                    Err(msg.into())
                }
            },
            Err(err) => {
                let msg = format!("Failed to make GET request to '{}'.", &self.file_url);
                error!("{} Got the following error: {}", msg, err);
                Err(msg.into())
            }
        }
    }
}

pub async fn find_games_xml(media_id: &str, locale: Locale) -> GenericResult<String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .build()?;
    let locale_str = Locale::as_code_str(&locale);
    let query: Vec<(&str, &str)> = vec![
        ("methodName", "FindGames"),
        ("Names", "MediaIds"),
        ("Values", media_id),
        ("Names", "DetailView"),
        ("Values", "5"),
        ("Names", "LegalLocale"),
        ("Values", locale_str),
        ("Names", "Locale"),
        ("Values", locale_str),
        ("Names", "MediaTypes"),
        ("Values", "1"),
        ("Names", "MediaTypes"),
        ("Values", "5"),
        ("Names", "MediaTypes"),
        ("Values", "18"),
        ("Names", "MediaTypes"),
        ("Values", "19"),
        ("Names", "MediaTypes"),
        ("Values", "20"),
        ("Names", "MediaTypes"),
        ("Values", "21"),
        ("Names", "MediaTypes"),
        ("Values", "22"),
        ("Names", "MediaTypes"),
        ("Values", "23"),
        ("Names", "MediaTypes"),
        ("Values", "24"),
        ("Names", "MediaTypes"),
        ("Values", "30"),
        ("Names", "MediaTypes"),
        ("Values", "34"),
        ("Names", "MediaTypes"),
        ("Values", "37"),
        ("Names", "MediaTypes"),
        ("Values", "45"),
        ("Names", "MediaTypes"),
        ("Values", "46"),
        ("Names", "MediaTypes"),
        ("Values", "47"),
        ("Names", "MediaTypes"),
        ("Values", "57"),
        ("Names", "MediaTypes"),
        ("Values", "59"),
        ("Names", "MediaTypes"),
        ("Values", "60"),
        ("Names", "MediaTypes"),
        ("Values", "61"),
        ("Names", "MediaTypes"),
        ("Values", "62"),
        ("Names", "MediaTypes"),
        ("Values", "63"),
        ("Names", "MediaTypes"),
        ("Values", "64"),
        ("Names", "MediaTypes"),
        ("Values", "66"),
        ("Names", "MediaTypes"),
        ("Values", "67"),
        ("Names", "OfferFilterLevel"),
        ("Values", "1"),
        ("Names", "OrderDirection"),
        ("Values", "1"),
        ("Names", "PageNum"),
        ("Values", "1"),
        ("Names", "PageSize"),
        ("Values", "100"),
        ("Names", "Store"),
        ("Values", "1"),
        ("Names", "UserTypes"),
        ("Values", "2"),
    ];
    let endpoint = "/Catalog/Catalog.asmx/Query";
    let req = client
        .get(format!("{}{}", API_ROOT, endpoint))
        .query(&query);
    match req.send().await {
        Ok(resp) => match resp.text().await {
            Ok(x) => Ok(x),
            Err(err) => {
                error!(
                    "Failed to get text from response. Got the following error: {}",
                    err
                );
                Err("Failed to get text from response.".into())
            }
        },
        Err(err) => {
            error!(
                "Failed to make GET request to '{}'. Got the following error: {}",
                endpoint, err
            );
            Err(format!("Failed to make GET request to '{}'.", endpoint).into())
        }
    }
}

pub async fn live_image_file_bytes(live_image: LiveImage) -> GenericResult<Vec<u8>> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .build()?;
    let req = client.get(&live_image.file_url);
    match req.send().await {
        Ok(resp) => match resp.bytes().await {
            Ok(x) => Ok(x.to_vec()),
            Err(err) => {
                let msg = "Failed to get image bytes from response.";
                error!("{} Got the following error: {}", msg, err);
                Err(msg.into())
            }
        },
        Err(err) => {
            let msg = format!("Failed to make GET request to '{}'.", &live_image.file_url);
            error!("{} Got the following error: {}", msg, err);
            Err(msg.into())
        }
    }
}

pub async fn live_images_for_title_id(
    title_id: usize,
    locale: Locale,
) -> GenericResult<Vec<LiveImage>> {
    live_images_from_xml(&find_games_xml(&media_id_for_title_id(title_id), locale).await?)
}

pub fn media_id_for_title_id(title_id: usize) -> String {
    format!("66acd000-77fe-1000-9115-d802{:08x}", title_id)
}

pub fn live_images_from_xml(xml: &str) -> GenericResult<Vec<LiveImage>> {
    let mut live_images: Vec<LiveImage> = Vec::new();
    let mut element_name: String = String::from("");
    let mut media_type: Option<usize> = None;
    let mut relationship_type: Option<usize> = None;
    let mut format: Option<usize> = None;
    let mut size: Option<usize> = None;
    let mut file_url: Option<String> = None;
    for reader_element in xml::reader::EventReader::from_str(xml) {
        match reader_element {
            Ok(xml::reader::XmlEvent::StartElement { name, .. }) => {
                element_name = name.local_name;
                if element_name == "image" {
                    media_type = None;
                    relationship_type = None;
                    format = None;
                    size = None;
                    file_url = None;
                }
            }
            Ok(xml::reader::XmlEvent::EndElement { name }) => {
                if name.local_name == "image" {
                    match (media_type, format, size, file_url.clone()) {
                        (Some(mt), Some(f), Some(s), Some(fu)) => {
                            let new_live_image = LiveImage {
                                media_type: mt,
                                relationship_type: relationship_type.clone(),
                                format: f,
                                size: s,
                                file_url: fu,
                            };
                            live_images.push(new_live_image);
                        }
                        _ => {
                            // TODO be more descriptive
                            warn!("Invalid image entry.");
                        }
                    }
                } else if name.local_name == "entry" {
                    break;
                }
            }
            Ok(xml::reader::XmlEvent::Characters(s)) => match element_name.as_str() {
                "imageMediaType" => {
                    media_type = match s.parse::<usize>() {
                        Ok(x) => Some(x),
                        Err(err) => {
                            warn!(
                                "Failed to convert imageMediaType '{}' to usize. Got the following error: {}",
                                s, err
                            );
                            None
                        }
                    };
                }
                "relationshipType" => {
                    relationship_type = match s.parse::<usize>() {
                        Ok(x) => Some(x),
                        Err(err) => {
                            warn!(
                                "Failed to convert relationshipType '{}' to usize. Got the following error: {}",
                                s, err
                            );
                            None
                        }
                    };
                }
                "format" => {
                    format = match s.parse::<usize>() {
                        Ok(x) => Some(x),
                        Err(err) => {
                            warn!(
                                "Failed to convert format '{}' to usize. Got the following error: {}",
                                s, err
                            );
                            None
                        }
                    }
                }
                "size" => {
                    size = match s.parse::<usize>() {
                        Ok(x) => Some(x),
                        Err(err) => {
                            warn!(
                                "Failed to convert size '{}' to usize. Got the following error: {}",
                                s, err
                            );
                            None
                        }
                    }
                }
                "fileUrl" => file_url = Some(s),
                _ => (),
            },
            Err(err) => {
                let msg = "Failed to parse xml.";
                error!("{} Got the following error: {}", msg, err);
                return Err(msg.into());
            }
            _ => {}
        }
    }
    Ok(live_images)
}

#[derive(Copy, Clone, Debug)]
#[repr(usize)]
pub enum Locale {
    AmEt,
    ArAe,
    ArBh,
    ArDz,
    ArEg,
    ArEh,
    ArGz,
    ArIq,
    ArJo,
    ArKw,
    ArLb,
    ArLy,
    ArMa,
    ArOm,
    ArQa,
    ArSa,
    ArSs,
    ArTn,
    ArWb,
    ArYe,
    BeBy,
    BgBg,
    BnBd,
    CsCz,
    DaDk,
    DeAt,
    DeCh,
    DeDe,
    DeLi,
    ElGr,
    EnAg,
    EnAi,
    EnAn,
    EnAo,
    EnAq,
    EnAs,
    EnAu,
    EnAw,
    EnAz,
    EnBa,
    EnBb,
    EnBf,
    EnBi,
    EnBj,
    EnBl,
    EnBm,
    EnBs,
    EnBt,
    EnBw,
    EnBz,
    EnCa,
    EnCc,
    EnCf,
    EnCk,
    EnCv,
    EnCx,
    EnCy,
    EnDj,
    EnEr,
    EnFj,
    EnFk,
    EnFm,
    EnGb,
    EnGd,
    EnGg,
    EnGh,
    EnGi,
    EnGm,
    EnGn,
    EnGq,
    EnGs,
    EnGu,
    EnGw,
    EnGy,
    EnHk,
    EnHm,
    EnIe,
    EnIm,
    EnIn,
    EnIo,
    EnJe,
    EnJm,
    EnKi,
    EnKn,
    EnKy,
    EnLa,
    EnLc,
    EnLr,
    EnLs,
    EnMd,
    EnMe,
    EnMh,
    EnMl,
    EnMm,
    EnMo,
    EnMp,
    EnMr,
    EnMs,
    EnMv,
    EnMw,
    EnMz,
    EnNa,
    EnNe,
    EnNf,
    EnNg,
    EnNr,
    EnNu,
    EnNz,
    EnPg,
    EnPh,
    EnPn,
    EnPs,
    EnPw,
    EnRe,
    EnRs,
    EnSb,
    EnSc,
    EnSg,
    EnSh,
    EnSl,
    EnSm,
    EnSo,
    EnSr,
    EnSt,
    EnSx,
    EnSz,
    EnTc,
    EnTd,
    EnTj,
    EnTk,
    EnTl,
    EnTo,
    EnTt,
    EnTv,
    EnTz,
    EnUg,
    EnUm,
    EnUs,
    EnUz,
    EnVa,
    EnVc,
    EnVg,
    EnVi,
    EnVu,
    EnWs,
    EnXe,
    EnXs,
    EnZa,
    EnZm,
    EnZw,
    EsAr,
    EsBo,
    EsCl,
    EsCo,
    EsCr,
    EsDm,
    EsDo,
    EsEc,
    EsEs,
    EsGt,
    EsHn,
    EsMx,
    EsNi,
    EsPa,
    EsPe,
    EsPy,
    EsSv,
    EsUy,
    EsVe,
    EtEe,
    FiFi,
    FoFo,
    FrAd,
    FrBe,
    FrCa,
    FrCd,
    FrCg,
    FrCh,
    FrCi,
    FrCm,
    FrFr,
    FrGa,
    FrGf,
    FrGp,
    FrHt,
    FrKm,
    FrMc,
    FrMf,
    FrMg,
    FrMq,
    FrMu,
    FrNc,
    FrPf,
    FrPm,
    FrTf,
    FrTg,
    FrWf,
    FrYt,
    HeIl,
    HrHr,
    HuHu,
    HyAm,
    IdId,
    IsIs,
    ItIt,
    JaJp,
    KaGe,
    KkKz,
    KlGl,
    KmKh,
    KoKr,
    KyKg,
    LbLu,
    LtLt,
    LvLv,
    MkMk,
    MnMn,
    MsBn,
    MsMy,
    MtMt,
    NbBv,
    NbNo,
    NbSj,
    NbXj,
    NeNp,
    NlBe,
    NlBq,
    NlCw,
    NlNl,
    PlPl,
    PsAf,
    PtBr,
    PtPt,
    RoRo,
    RuRu,
    RwRw,
    SiLk,
    SkSk,
    SlSi,
    SqAl,
    SqXk,
    SvAx,
    SvSe,
    SwKe,
    ThTh,
    TkTm,
    TrTr,
    UkUa,
    UrPk,
    ViVn,
    WoSn,
    ZhCn,
    ZhHk,
    ZhTw,
}

impl Locale {
    pub fn as_code_str(&self) -> &'static str {
        match self {
            Locale::AmEt => "am-ET",
            Locale::ArAe => "ar-AE",
            Locale::ArBh => "ar-BH",
            Locale::ArDz => "ar-DZ",
            Locale::ArEg => "ar-EG",
            Locale::ArEh => "ar-EH",
            Locale::ArGz => "ar-GZ",
            Locale::ArIq => "ar-IQ",
            Locale::ArJo => "ar-JO",
            Locale::ArKw => "ar-KW",
            Locale::ArLb => "ar-LB",
            Locale::ArLy => "ar-LY",
            Locale::ArMa => "ar-MA",
            Locale::ArOm => "ar-OM",
            Locale::ArQa => "ar-QA",
            Locale::ArSa => "ar-SA",
            Locale::ArSs => "ar-SS",
            Locale::ArTn => "ar-TN",
            Locale::ArWb => "ar-WB",
            Locale::ArYe => "ar-YE",
            Locale::BeBy => "be-BY",
            Locale::BgBg => "bg-BG",
            Locale::BnBd => "bn-BD",
            Locale::CsCz => "cs-CZ",
            Locale::DaDk => "da-DK",
            Locale::DeAt => "de-AT",
            Locale::DeCh => "de-CH",
            Locale::DeDe => "de-DE",
            Locale::DeLi => "de-LI",
            Locale::ElGr => "el-GR",
            Locale::EnAg => "en-AG",
            Locale::EnAi => "en-AI",
            Locale::EnAn => "en-AN",
            Locale::EnAo => "en-AO",
            Locale::EnAq => "en-AQ",
            Locale::EnAs => "en-AS",
            Locale::EnAu => "en-AU",
            Locale::EnAw => "en-AW",
            Locale::EnAz => "en-AZ",
            Locale::EnBa => "en-BA",
            Locale::EnBb => "en-BB",
            Locale::EnBf => "en-BF",
            Locale::EnBi => "en-BI",
            Locale::EnBj => "en-BJ",
            Locale::EnBl => "en-BL",
            Locale::EnBm => "en-BM",
            Locale::EnBs => "en-BS",
            Locale::EnBt => "en-BT",
            Locale::EnBw => "en-BW",
            Locale::EnBz => "en-BZ",
            Locale::EnCa => "en-CA",
            Locale::EnCc => "en-CC",
            Locale::EnCf => "en-CF",
            Locale::EnCk => "en-CK",
            Locale::EnCv => "en-CV",
            Locale::EnCx => "en-CX",
            Locale::EnCy => "en-CY",
            Locale::EnDj => "en-DJ",
            Locale::EnEr => "en-ER",
            Locale::EnFj => "en-FJ",
            Locale::EnFk => "en-FK",
            Locale::EnFm => "en-FM",
            Locale::EnGb => "en-GB",
            Locale::EnGd => "en-GD",
            Locale::EnGg => "en-GG",
            Locale::EnGh => "en-GH",
            Locale::EnGi => "en-GI",
            Locale::EnGm => "en-GM",
            Locale::EnGn => "en-GN",
            Locale::EnGq => "en-GQ",
            Locale::EnGs => "en-GS",
            Locale::EnGu => "en-GU",
            Locale::EnGw => "en-GW",
            Locale::EnGy => "en-GY",
            Locale::EnHk => "en-HK",
            Locale::EnHm => "en-HM",
            Locale::EnIe => "en-IE",
            Locale::EnIm => "en-IM",
            Locale::EnIn => "en-IN",
            Locale::EnIo => "en-IO",
            Locale::EnJe => "en-JE",
            Locale::EnJm => "en-JM",
            Locale::EnKi => "en-KI",
            Locale::EnKn => "en-KN",
            Locale::EnKy => "en-KY",
            Locale::EnLa => "en-LA",
            Locale::EnLc => "en-LC",
            Locale::EnLr => "en-LR",
            Locale::EnLs => "en-LS",
            Locale::EnMd => "en-MD",
            Locale::EnMe => "en-ME",
            Locale::EnMh => "en-MH",
            Locale::EnMl => "en-ML",
            Locale::EnMm => "en-MM",
            Locale::EnMo => "en-MO",
            Locale::EnMp => "en-MP",
            Locale::EnMr => "en-MR",
            Locale::EnMs => "en-MS",
            Locale::EnMv => "en-MV",
            Locale::EnMw => "en-MW",
            Locale::EnMz => "en-MZ",
            Locale::EnNa => "en-NA",
            Locale::EnNe => "en-NE",
            Locale::EnNf => "en-NF",
            Locale::EnNg => "en-NG",
            Locale::EnNr => "en-NR",
            Locale::EnNu => "en-NU",
            Locale::EnNz => "en-NZ",
            Locale::EnPg => "en-PG",
            Locale::EnPh => "en-PH",
            Locale::EnPn => "en-PN",
            Locale::EnPs => "en-PS",
            Locale::EnPw => "en-PW",
            Locale::EnRe => "en-RE",
            Locale::EnRs => "en-RS",
            Locale::EnSb => "en-SB",
            Locale::EnSc => "en-SC",
            Locale::EnSg => "en-SG",
            Locale::EnSh => "en-SH",
            Locale::EnSl => "en-SL",
            Locale::EnSm => "en-SM",
            Locale::EnSo => "en-SO",
            Locale::EnSr => "en-SR",
            Locale::EnSt => "en-ST",
            Locale::EnSx => "en-SX",
            Locale::EnSz => "en-SZ",
            Locale::EnTc => "en-TC",
            Locale::EnTd => "en-TD",
            Locale::EnTj => "en-TJ",
            Locale::EnTk => "en-TK",
            Locale::EnTl => "en-TL",
            Locale::EnTo => "en-TO",
            Locale::EnTt => "en-TT",
            Locale::EnTv => "en-TV",
            Locale::EnTz => "en-TZ",
            Locale::EnUg => "en-UG",
            Locale::EnUm => "en-UM",
            Locale::EnUs => "en-US",
            Locale::EnUz => "en-UZ",
            Locale::EnVa => "en-VA",
            Locale::EnVc => "en-VC",
            Locale::EnVg => "en-VG",
            Locale::EnVi => "en-VI",
            Locale::EnVu => "en-VU",
            Locale::EnWs => "en-WS",
            Locale::EnXe => "en-XE",
            Locale::EnXs => "en-XS",
            Locale::EnZa => "en-ZA",
            Locale::EnZm => "en-ZM",
            Locale::EnZw => "en-ZW",
            Locale::EsAr => "es-AR",
            Locale::EsBo => "es-BO",
            Locale::EsCl => "es-CL",
            Locale::EsCo => "es-CO",
            Locale::EsCr => "es-CR",
            Locale::EsDm => "es-DM",
            Locale::EsDo => "es-DO",
            Locale::EsEc => "es-EC",
            Locale::EsEs => "es-ES",
            Locale::EsGt => "es-GT",
            Locale::EsHn => "es-HN",
            Locale::EsMx => "es-MX",
            Locale::EsNi => "es-NI",
            Locale::EsPa => "es-PA",
            Locale::EsPe => "es-PE",
            Locale::EsPy => "es-PY",
            Locale::EsSv => "es-SV",
            Locale::EsUy => "es-UY",
            Locale::EsVe => "es-VE",
            Locale::EtEe => "et-EE",
            Locale::FiFi => "fi-FI",
            Locale::FoFo => "fo-FO",
            Locale::FrAd => "fr-AD",
            Locale::FrBe => "fr-BE",
            Locale::FrCa => "fr-CA",
            Locale::FrCd => "fr-CD",
            Locale::FrCg => "fr-CG",
            Locale::FrCh => "fr-CH",
            Locale::FrCi => "fr-CI",
            Locale::FrCm => "fr-CM",
            Locale::FrFr => "fr-FR",
            Locale::FrGa => "fr-GA",
            Locale::FrGf => "fr-GF",
            Locale::FrGp => "fr-GP",
            Locale::FrHt => "fr-HT",
            Locale::FrKm => "fr-KM",
            Locale::FrMc => "fr-MC",
            Locale::FrMf => "fr-MF",
            Locale::FrMg => "fr-MG",
            Locale::FrMq => "fr-MQ",
            Locale::FrMu => "fr-MU",
            Locale::FrNc => "fr-NC",
            Locale::FrPf => "fr-PF",
            Locale::FrPm => "fr-PM",
            Locale::FrTf => "fr-TF",
            Locale::FrTg => "fr-TG",
            Locale::FrWf => "fr-WF",
            Locale::FrYt => "fr-YT",
            Locale::HeIl => "he-IL",
            Locale::HrHr => "hr-HR",
            Locale::HuHu => "hu-HU",
            Locale::HyAm => "hy-AM",
            Locale::IdId => "id-ID",
            Locale::IsIs => "is-IS",
            Locale::ItIt => "it-IT",
            Locale::JaJp => "ja-JP",
            Locale::KaGe => "ka-GE",
            Locale::KkKz => "kk-KZ",
            Locale::KlGl => "kl-GL",
            Locale::KmKh => "km-KH",
            Locale::KoKr => "ko-KR",
            Locale::KyKg => "ky-KG",
            Locale::LbLu => "lb-LU",
            Locale::LtLt => "lt-LT",
            Locale::LvLv => "lv-LV",
            Locale::MkMk => "mk-MK",
            Locale::MnMn => "mn-MN",
            Locale::MsBn => "ms-BN",
            Locale::MsMy => "ms-MY",
            Locale::MtMt => "mt-MT",
            Locale::NbBv => "nb-BV",
            Locale::NbNo => "nb-NO",
            Locale::NbSj => "nb-SJ",
            Locale::NbXj => "nb-XJ",
            Locale::NeNp => "ne-NP",
            Locale::NlBe => "nl-BE",
            Locale::NlBq => "nl-BQ",
            Locale::NlCw => "nl-CW",
            Locale::NlNl => "nl-NL",
            Locale::PlPl => "pl-PL",
            Locale::PsAf => "ps-AF",
            Locale::PtBr => "pt-BR",
            Locale::PtPt => "pt-PT",
            Locale::RoRo => "ro-RO",
            Locale::RuRu => "ru-RU",
            Locale::RwRw => "rw-RW",
            Locale::SiLk => "si-LK",
            Locale::SkSk => "sk-SK",
            Locale::SlSi => "sl-SI",
            Locale::SqAl => "sq-AL",
            Locale::SqXk => "sq-XK",
            Locale::SvAx => "sv-AX",
            Locale::SvSe => "sv-SE",
            Locale::SwKe => "sw-KE",
            Locale::ThTh => "th-TH",
            Locale::TkTm => "tk-TM",
            Locale::TrTr => "tr-TR",
            Locale::UkUa => "uk-UA",
            Locale::UrPk => "ur-PK",
            Locale::ViVn => "vi-VN",
            Locale::WoSn => "wo-SN",
            Locale::ZhCn => "zh-CN",
            Locale::ZhHk => "zh-HK",
            Locale::ZhTw => "zh-TW",
        }
    }

    pub fn from_code_str(s: &str) -> GenericResult<Self> {
        match s {
            "am-ET" => Ok(Locale::AmEt),
            "ar-AE" => Ok(Locale::ArAe),
            "ar-BH" => Ok(Locale::ArBh),
            "ar-DZ" => Ok(Locale::ArDz),
            "ar-EG" => Ok(Locale::ArEg),
            "ar-EH" => Ok(Locale::ArEh),
            "ar-GZ" => Ok(Locale::ArGz),
            "ar-IQ" => Ok(Locale::ArIq),
            "ar-JO" => Ok(Locale::ArJo),
            "ar-KW" => Ok(Locale::ArKw),
            "ar-LB" => Ok(Locale::ArLb),
            "ar-LY" => Ok(Locale::ArLy),
            "ar-MA" => Ok(Locale::ArMa),
            "ar-OM" => Ok(Locale::ArOm),
            "ar-QA" => Ok(Locale::ArQa),
            "ar-SA" => Ok(Locale::ArSa),
            "ar-SS" => Ok(Locale::ArSs),
            "ar-TN" => Ok(Locale::ArTn),
            "ar-WB" => Ok(Locale::ArWb),
            "ar-YE" => Ok(Locale::ArYe),
            "be-BY" => Ok(Locale::BeBy),
            "bg-BG" => Ok(Locale::BgBg),
            "bn-BD" => Ok(Locale::BnBd),
            "cs-CZ" => Ok(Locale::CsCz),
            "da-DK" => Ok(Locale::DaDk),
            "de-AT" => Ok(Locale::DeAt),
            "de-CH" => Ok(Locale::DeCh),
            "de-DE" => Ok(Locale::DeDe),
            "de-LI" => Ok(Locale::DeLi),
            "el-GR" => Ok(Locale::ElGr),
            "en-AG" => Ok(Locale::EnAg),
            "en-AI" => Ok(Locale::EnAi),
            "en-AN" => Ok(Locale::EnAn),
            "en-AO" => Ok(Locale::EnAo),
            "en-AQ" => Ok(Locale::EnAq),
            "en-AS" => Ok(Locale::EnAs),
            "en-AU" => Ok(Locale::EnAu),
            "en-AW" => Ok(Locale::EnAw),
            "en-AZ" => Ok(Locale::EnAz),
            "en-BA" => Ok(Locale::EnBa),
            "en-BB" => Ok(Locale::EnBb),
            "en-BF" => Ok(Locale::EnBf),
            "en-BI" => Ok(Locale::EnBi),
            "en-BJ" => Ok(Locale::EnBj),
            "en-BL" => Ok(Locale::EnBl),
            "en-BM" => Ok(Locale::EnBm),
            "en-BS" => Ok(Locale::EnBs),
            "en-BT" => Ok(Locale::EnBt),
            "en-BW" => Ok(Locale::EnBw),
            "en-BZ" => Ok(Locale::EnBz),
            "en-CA" => Ok(Locale::EnCa),
            "en-CC" => Ok(Locale::EnCc),
            "en-CF" => Ok(Locale::EnCf),
            "en-CK" => Ok(Locale::EnCk),
            "en-CV" => Ok(Locale::EnCv),
            "en-CX" => Ok(Locale::EnCx),
            "en-CY" => Ok(Locale::EnCy),
            "en-DJ" => Ok(Locale::EnDj),
            "en-ER" => Ok(Locale::EnEr),
            "en-FJ" => Ok(Locale::EnFj),
            "en-FK" => Ok(Locale::EnFk),
            "en-FM" => Ok(Locale::EnFm),
            "en-GB" => Ok(Locale::EnGb),
            "en-GD" => Ok(Locale::EnGd),
            "en-GG" => Ok(Locale::EnGg),
            "en-GH" => Ok(Locale::EnGh),
            "en-GI" => Ok(Locale::EnGi),
            "en-GM" => Ok(Locale::EnGm),
            "en-GN" => Ok(Locale::EnGn),
            "en-GQ" => Ok(Locale::EnGq),
            "en-GS" => Ok(Locale::EnGs),
            "en-GU" => Ok(Locale::EnGu),
            "en-GW" => Ok(Locale::EnGw),
            "en-GY" => Ok(Locale::EnGy),
            "en-HK" => Ok(Locale::EnHk),
            "en-HM" => Ok(Locale::EnHm),
            "en-IE" => Ok(Locale::EnIe),
            "en-IM" => Ok(Locale::EnIm),
            "en-IN" => Ok(Locale::EnIn),
            "en-IO" => Ok(Locale::EnIo),
            "en-JE" => Ok(Locale::EnJe),
            "en-JM" => Ok(Locale::EnJm),
            "en-KI" => Ok(Locale::EnKi),
            "en-KN" => Ok(Locale::EnKn),
            "en-KY" => Ok(Locale::EnKy),
            "en-LA" => Ok(Locale::EnLa),
            "en-LC" => Ok(Locale::EnLc),
            "en-LR" => Ok(Locale::EnLr),
            "en-LS" => Ok(Locale::EnLs),
            "en-MD" => Ok(Locale::EnMd),
            "en-ME" => Ok(Locale::EnMe),
            "en-MH" => Ok(Locale::EnMh),
            "en-ML" => Ok(Locale::EnMl),
            "en-MM" => Ok(Locale::EnMm),
            "en-MO" => Ok(Locale::EnMo),
            "en-MP" => Ok(Locale::EnMp),
            "en-MR" => Ok(Locale::EnMr),
            "en-MS" => Ok(Locale::EnMs),
            "en-MV" => Ok(Locale::EnMv),
            "en-MW" => Ok(Locale::EnMw),
            "en-MZ" => Ok(Locale::EnMz),
            "en-NA" => Ok(Locale::EnNa),
            "en-NE" => Ok(Locale::EnNe),
            "en-NF" => Ok(Locale::EnNf),
            "en-NG" => Ok(Locale::EnNg),
            "en-NR" => Ok(Locale::EnNr),
            "en-NU" => Ok(Locale::EnNu),
            "en-NZ" => Ok(Locale::EnNz),
            "en-PG" => Ok(Locale::EnPg),
            "en-PH" => Ok(Locale::EnPh),
            "en-PN" => Ok(Locale::EnPn),
            "en-PS" => Ok(Locale::EnPs),
            "en-PW" => Ok(Locale::EnPw),
            "en-RE" => Ok(Locale::EnRe),
            "en-RS" => Ok(Locale::EnRs),
            "en-SB" => Ok(Locale::EnSb),
            "en-SC" => Ok(Locale::EnSc),
            "en-SG" => Ok(Locale::EnSg),
            "en-SH" => Ok(Locale::EnSh),
            "en-SL" => Ok(Locale::EnSl),
            "en-SM" => Ok(Locale::EnSm),
            "en-SO" => Ok(Locale::EnSo),
            "en-SR" => Ok(Locale::EnSr),
            "en-ST" => Ok(Locale::EnSt),
            "en-SX" => Ok(Locale::EnSx),
            "en-SZ" => Ok(Locale::EnSz),
            "en-TC" => Ok(Locale::EnTc),
            "en-TD" => Ok(Locale::EnTd),
            "en-TJ" => Ok(Locale::EnTj),
            "en-TK" => Ok(Locale::EnTk),
            "en-TL" => Ok(Locale::EnTl),
            "en-TO" => Ok(Locale::EnTo),
            "en-TT" => Ok(Locale::EnTt),
            "en-TV" => Ok(Locale::EnTv),
            "en-TZ" => Ok(Locale::EnTz),
            "en-UG" => Ok(Locale::EnUg),
            "en-UM" => Ok(Locale::EnUm),
            "en-US" => Ok(Locale::EnUs),
            "en-UZ" => Ok(Locale::EnUz),
            "en-VA" => Ok(Locale::EnVa),
            "en-VC" => Ok(Locale::EnVc),
            "en-VG" => Ok(Locale::EnVg),
            "en-VI" => Ok(Locale::EnVi),
            "en-VU" => Ok(Locale::EnVu),
            "en-WS" => Ok(Locale::EnWs),
            "en-XE" => Ok(Locale::EnXe),
            "en-XS" => Ok(Locale::EnXs),
            "en-ZA" => Ok(Locale::EnZa),
            "en-ZM" => Ok(Locale::EnZm),
            "en-ZW" => Ok(Locale::EnZw),
            "es-AR" => Ok(Locale::EsAr),
            "es-BO" => Ok(Locale::EsBo),
            "es-CL" => Ok(Locale::EsCl),
            "es-CO" => Ok(Locale::EsCo),
            "es-CR" => Ok(Locale::EsCr),
            "es-DM" => Ok(Locale::EsDm),
            "es-DO" => Ok(Locale::EsDo),
            "es-EC" => Ok(Locale::EsEc),
            "es-ES" => Ok(Locale::EsEs),
            "es-GT" => Ok(Locale::EsGt),
            "es-HN" => Ok(Locale::EsHn),
            "es-MX" => Ok(Locale::EsMx),
            "es-NI" => Ok(Locale::EsNi),
            "es-PA" => Ok(Locale::EsPa),
            "es-PE" => Ok(Locale::EsPe),
            "es-PY" => Ok(Locale::EsPy),
            "es-SV" => Ok(Locale::EsSv),
            "es-UY" => Ok(Locale::EsUy),
            "es-VE" => Ok(Locale::EsVe),
            "et-EE" => Ok(Locale::EtEe),
            "fi-FI" => Ok(Locale::FiFi),
            "fo-FO" => Ok(Locale::FoFo),
            "fr-AD" => Ok(Locale::FrAd),
            "fr-BE" => Ok(Locale::FrBe),
            "fr-CA" => Ok(Locale::FrCa),
            "fr-CD" => Ok(Locale::FrCd),
            "fr-CG" => Ok(Locale::FrCg),
            "fr-CH" => Ok(Locale::FrCh),
            "fr-CI" => Ok(Locale::FrCi),
            "fr-CM" => Ok(Locale::FrCm),
            "fr-FR" => Ok(Locale::FrFr),
            "fr-GA" => Ok(Locale::FrGa),
            "fr-GF" => Ok(Locale::FrGf),
            "fr-GP" => Ok(Locale::FrGp),
            "fr-HT" => Ok(Locale::FrHt),
            "fr-KM" => Ok(Locale::FrKm),
            "fr-MC" => Ok(Locale::FrMc),
            "fr-MF" => Ok(Locale::FrMf),
            "fr-MG" => Ok(Locale::FrMg),
            "fr-MQ" => Ok(Locale::FrMq),
            "fr-MU" => Ok(Locale::FrMu),
            "fr-NC" => Ok(Locale::FrNc),
            "fr-PF" => Ok(Locale::FrPf),
            "fr-PM" => Ok(Locale::FrPm),
            "fr-TF" => Ok(Locale::FrTf),
            "fr-TG" => Ok(Locale::FrTg),
            "fr-WF" => Ok(Locale::FrWf),
            "fr-YT" => Ok(Locale::FrYt),
            "he-IL" => Ok(Locale::HeIl),
            "hr-HR" => Ok(Locale::HrHr),
            "hu-HU" => Ok(Locale::HuHu),
            "hy-AM" => Ok(Locale::HyAm),
            "id-ID" => Ok(Locale::IdId),
            "is-IS" => Ok(Locale::IsIs),
            "it-IT" => Ok(Locale::ItIt),
            "ja-JP" => Ok(Locale::JaJp),
            "ka-GE" => Ok(Locale::KaGe),
            "kk-KZ" => Ok(Locale::KkKz),
            "kl-GL" => Ok(Locale::KlGl),
            "km-KH" => Ok(Locale::KmKh),
            "ko-KR" => Ok(Locale::KoKr),
            "ky-KG" => Ok(Locale::KyKg),
            "lb-LU" => Ok(Locale::LbLu),
            "lt-LT" => Ok(Locale::LtLt),
            "lv-LV" => Ok(Locale::LvLv),
            "mk-MK" => Ok(Locale::MkMk),
            "mn-MN" => Ok(Locale::MnMn),
            "ms-BN" => Ok(Locale::MsBn),
            "ms-MY" => Ok(Locale::MsMy),
            "mt-MT" => Ok(Locale::MtMt),
            "nb-BV" => Ok(Locale::NbBv),
            "nb-NO" => Ok(Locale::NbNo),
            "nb-SJ" => Ok(Locale::NbSj),
            "nb-XJ" => Ok(Locale::NbXj),
            "ne-NP" => Ok(Locale::NeNp),
            "nl-BE" => Ok(Locale::NlBe),
            "nl-BQ" => Ok(Locale::NlBq),
            "nl-CW" => Ok(Locale::NlCw),
            "nl-NL" => Ok(Locale::NlNl),
            "pl-PL" => Ok(Locale::PlPl),
            "ps-AF" => Ok(Locale::PsAf),
            "pt-BR" => Ok(Locale::PtBr),
            "pt-PT" => Ok(Locale::PtPt),
            "ro-RO" => Ok(Locale::RoRo),
            "ru-RU" => Ok(Locale::RuRu),
            "rw-RW" => Ok(Locale::RwRw),
            "si-LK" => Ok(Locale::SiLk),
            "sk-SK" => Ok(Locale::SkSk),
            "sl-SI" => Ok(Locale::SlSi),
            "sq-AL" => Ok(Locale::SqAl),
            "sq-XK" => Ok(Locale::SqXk),
            "sv-AX" => Ok(Locale::SvAx),
            "sv-SE" => Ok(Locale::SvSe),
            "sw-KE" => Ok(Locale::SwKe),
            "th-TH" => Ok(Locale::ThTh),
            "tk-TM" => Ok(Locale::TkTm),
            "tr-TR" => Ok(Locale::TrTr),
            "uk-UA" => Ok(Locale::UkUa),
            "ur-PK" => Ok(Locale::UrPk),
            "vi-VN" => Ok(Locale::ViVn),
            "wo-SN" => Ok(Locale::WoSn),
            "zh-CN" => Ok(Locale::ZhCn),
            "zh-HK" => Ok(Locale::ZhHk),
            "zh-TW" => Ok(Locale::ZhTw),
            _ => Err(format!("Invalid locale code: {}", s).into()),
        }
    }

    pub fn as_territory_str(&self) -> &'static str {
        match self {
            Locale::AmEt => "Ethiopia",
            Locale::ArAe => "United Arab Emirates",
            Locale::ArBh => "Bahrain",
            Locale::ArDz => "Algeria",
            Locale::ArEg => "Egypt",
            Locale::ArEh => "Western Sahara",
            Locale::ArGz => "Gaza Strip",
            Locale::ArIq => "Iraq",
            Locale::ArJo => "Jordan",
            Locale::ArKw => "Kuwait",
            Locale::ArLb => "Lebanon",
            Locale::ArLy => "Libya",
            Locale::ArMa => "Morocco",
            Locale::ArOm => "Oman",
            Locale::ArQa => "Qatar",
            Locale::ArSa => "Saudi Arabia",
            Locale::ArSs => "South Sudan",
            Locale::ArTn => "Tunisia",
            Locale::ArWb => "West Bank",
            Locale::ArYe => "Yemen",
            Locale::BeBy => "Belarus",
            Locale::BgBg => "Bulgaria",
            Locale::BnBd => "Bangladesh",
            Locale::CsCz => "Česká republika",
            Locale::DaDk => "Danmark",
            Locale::DeAt => "Österreich",
            Locale::DeCh => "Schweiz",
            Locale::DeDe => "Deutschland",
            Locale::DeLi => "Liechtenstein",
            Locale::ElGr => "Ελλάδα",
            Locale::EnAg => "Antigua and Barbuda",
            Locale::EnAi => "Anguilla",
            Locale::EnAn => "Netherlands Antilles",
            Locale::EnAo => "Angola",
            Locale::EnAq => "Antarctica",
            Locale::EnAs => "American Samoa",
            Locale::EnAu => "Australia",
            Locale::EnAw => "Aruba",
            Locale::EnAz => "Azerbaijan",
            Locale::EnBa => "Bosnia and Herzegovina",
            Locale::EnBb => "Barbados",
            Locale::EnBf => "Burkina Faso",
            Locale::EnBi => "Burundi",
            Locale::EnBj => "Benin",
            Locale::EnBl => "Saint Barthélemy",
            Locale::EnBm => "Bermuda",
            Locale::EnBs => "Bahamas, The",
            Locale::EnBt => "Bhutan",
            Locale::EnBw => "Botswana",
            Locale::EnBz => "Belize",
            Locale::EnCa => "Canada (English)",
            Locale::EnCc => "Cocos (Keeling) Islands",
            Locale::EnCf => "Central African Republic",
            Locale::EnCk => "Cook Islands",
            Locale::EnCv => "Cape Verde",
            Locale::EnCx => "Christmas Island",
            Locale::EnCy => "Cyprus",
            Locale::EnDj => "Djibouti",
            Locale::EnEr => "Eritrea",
            Locale::EnFj => "Fiji Islands",
            Locale::EnFk => "Falkland Islands (Islas Malvinas)",
            Locale::EnFm => "Micronesia",
            Locale::EnGb => "United Kingdom",
            Locale::EnGd => "Grenada",
            Locale::EnGg => "Channel Islands - Guernsey",
            Locale::EnGh => "Ghana",
            Locale::EnGi => "Gibraltar",
            Locale::EnGm => "Gambia, The",
            Locale::EnGn => "Guinea",
            Locale::EnGq => "Equatorial Guinea",
            Locale::EnGs => "S. Georgia and S. Sandwich Isls.",
            Locale::EnGu => "Guam",
            Locale::EnGw => "Guinea-Bissau",
            Locale::EnGy => "Guyana",
            Locale::EnHk => "Hong Kong S.A.R. (English)",
            Locale::EnHm => "Heard and McDonald Islands",
            Locale::EnIe => "Ireland",
            Locale::EnIm => "Isle of Man",
            Locale::EnIn => "India",
            Locale::EnIo => "British Indian Ocean Territory",
            Locale::EnJe => "Channel Islands - Jersey",
            Locale::EnJm => "Jamaica",
            Locale::EnKi => "Kiribati",
            Locale::EnKn => "St. Kitts and Nevis",
            Locale::EnKy => "Cayman Islands",
            Locale::EnLa => "Laos",
            Locale::EnLc => "St. Lucia",
            Locale::EnLr => "Liberia",
            Locale::EnLs => "Lesotho",
            Locale::EnMd => "Moldova",
            Locale::EnMe => "Montenegro",
            Locale::EnMh => "Marshall Islands",
            Locale::EnMl => "Mali",
            Locale::EnMm => "Myanmar",
            Locale::EnMo => "Macau SAR",
            Locale::EnMp => "Northern Mariana Islands",
            Locale::EnMr => "Mauritania",
            Locale::EnMs => "Montserrat",
            Locale::EnMv => "Maldives",
            Locale::EnMw => "Malawi",
            Locale::EnMz => "Mozambique",
            Locale::EnNa => "Namibia",
            Locale::EnNe => "Niger",
            Locale::EnNf => "Norfolk Island",
            Locale::EnNg => "Nigeria",
            Locale::EnNr => "Nauru",
            Locale::EnNu => "Niue",
            Locale::EnNz => "New Zealand",
            Locale::EnPg => "Papua New Guinea",
            Locale::EnPh => "Philippines",
            Locale::EnPn => "Pitcairn Islands",
            Locale::EnPs => "Palestinian Authority",
            Locale::EnPw => "Palau",
            Locale::EnRe => "Reunion",
            Locale::EnRs => "Serbia",
            Locale::EnSb => "Solomon Islands",
            Locale::EnSc => "Seychelles",
            Locale::EnSg => "Singapore",
            Locale::EnSh => "St. Helena",
            Locale::EnSl => "Sierra Leone",
            Locale::EnSm => "San Marino",
            Locale::EnSo => "Somalia",
            Locale::EnSr => "Suriname",
            Locale::EnSt => "Sao Tome and Principe",
            Locale::EnSx => "Sint Maarten",
            Locale::EnSz => "Swaziland",
            Locale::EnTc => "Turks and Caicos Islands",
            Locale::EnTd => "Chad",
            Locale::EnTj => "Tajikistan",
            Locale::EnTk => "Tokelau",
            Locale::EnTl => "Timor-Leste",
            Locale::EnTo => "Tonga",
            Locale::EnTt => "Trinidad and Tobago",
            Locale::EnTv => "Tuvalu",
            Locale::EnTz => "Tanzania",
            Locale::EnUg => "Uganda",
            Locale::EnUm => "US Minor Outlying Islands",
            Locale::EnUs => "United States",
            Locale::EnUz => "Uzbekistan",
            Locale::EnVa => "Vatican City",
            Locale::EnVc => "St. Vincent and the Grenadines",
            Locale::EnVg => "Virgin Islands, British",
            Locale::EnVi => "Virgin Islands, U.S.",
            Locale::EnVu => "Vanuatu",
            Locale::EnWs => "Samoa",
            Locale::EnXe => "Sint Eustatius",
            Locale::EnXs => "Saba",
            Locale::EnZa => "South Africa",
            Locale::EnZm => "Zambia",
            Locale::EnZw => "Zimbabwe",
            Locale::EsAr => "Argentina",
            Locale::EsBo => "Bolivia",
            Locale::EsCl => "Chile",
            Locale::EsCo => "Colombia",
            Locale::EsCr => "Costa Rica",
            Locale::EsDm => "Dominica",
            Locale::EsDo => "República Dominicana",
            Locale::EsEc => "Ecuador",
            Locale::EsEs => "España",
            Locale::EsGt => "Guatemala",
            Locale::EsHn => "Honduras",
            Locale::EsMx => "México",
            Locale::EsNi => "Nicaragua",
            Locale::EsPa => "Panamá",
            Locale::EsPe => "Peru",
            Locale::EsPy => "Paraguay",
            Locale::EsSv => "El Salvador",
            Locale::EsUy => "Uruguay",
            Locale::EsVe => "Venezuela",
            Locale::EtEe => "Estonia",
            Locale::FiFi => "Suomi",
            Locale::FoFo => "Faroe Islands",
            Locale::FrAd => "Andorra",
            Locale::FrBe => "Belgique",
            Locale::FrCa => "Canada (Français)",
            Locale::FrCd => "Congo (DRC)",
            Locale::FrCg => "Congo",
            Locale::FrCh => "Suisse",
            Locale::FrCi => "Côte d'Ivoire",
            Locale::FrCm => "Cameroon",
            Locale::FrFr => "France",
            Locale::FrGa => "Gabon",
            Locale::FrGf => "French Guiana",
            Locale::FrGp => "Guadeloupe",
            Locale::FrHt => "Haiti",
            Locale::FrKm => "Comoros",
            Locale::FrMc => "Monaco",
            Locale::FrMf => "Saint Martin",
            Locale::FrMg => "Madagascar",
            Locale::FrMq => "Martinique",
            Locale::FrMu => "Mauritius",
            Locale::FrNc => "New Caledonia",
            Locale::FrPf => "French Polynesia",
            Locale::FrPm => "St. Pierre and Miquelon",
            Locale::FrTf => "French Southern Territories",
            Locale::FrTg => "Togo",
            Locale::FrWf => "Wallis and Futuna",
            Locale::FrYt => "Mayotte",
            Locale::HeIl => "Israel",
            Locale::HrHr => "Croatia",
            Locale::HuHu => "Magyarország",
            Locale::HyAm => "Armenia",
            Locale::IdId => "Indonesia",
            Locale::IsIs => "Iceland",
            Locale::ItIt => "Italia",
            Locale::JaJp => "日本 (Japan)",
            Locale::KaGe => "Georgia",
            Locale::KkKz => "Kazakhstan",
            Locale::KlGl => "Greenland",
            Locale::KmKh => "Cambodia",
            Locale::KoKr => "대한민국 (Korea)",
            Locale::KyKg => "Kyrgyzstan",
            Locale::LbLu => "Luxembourg",
            Locale::LtLt => "Lithuania",
            Locale::LvLv => "Latvia",
            Locale::MkMk => "Macedonia, Former Yugoslvaian Republic of",
            Locale::MnMn => "Mongolia",
            Locale::MsBn => "Brunei",
            Locale::MsMy => "Malaysia",
            Locale::MtMt => "Malta",
            Locale::NbBv => "Bouvet Island",
            Locale::NbNo => "Norge",
            Locale::NbSj => "Svalbard",
            Locale::NbXj => "Jan Mayen",
            Locale::NeNp => "Nepal",
            Locale::NlBe => "België",
            Locale::NlBq => "Bonaire",
            Locale::NlCw => "Curaçao",
            Locale::NlNl => "Nederland",
            Locale::PlPl => "Polska",
            Locale::PsAf => "Afghanistan",
            Locale::PtBr => "Brasil",
            Locale::PtPt => "Portugal",
            Locale::RoRo => "Romania",
            Locale::RuRu => "Pоссия",
            Locale::RwRw => "Rwanda",
            Locale::SiLk => "Sri Lanka",
            Locale::SkSk => "Slovakia",
            Locale::SlSi => "Slovenia",
            Locale::SqAl => "Albania",
            Locale::SqXk => "Kosovo",
            Locale::SvAx => "Aland Islands",
            Locale::SvSe => "Sverige",
            Locale::SwKe => "Kenya",
            Locale::ThTh => "Thailand",
            Locale::TkTm => "Turkmenistan",
            Locale::TrTr => "Türkiye",
            Locale::UkUa => "Ukraine",
            Locale::UrPk => "Pakistan",
            Locale::ViVn => "Vietnam",
            Locale::WoSn => "Senegal",
            Locale::ZhCn => "中华人民共和国 (China)",
            Locale::ZhHk => "Hong Kong S.A.R. (香港)",
            Locale::ZhTw => "台灣 (Taiwan)",
        }
    }

    pub fn from_territory_str(s: &str) -> GenericResult<Self> {
        match s {
            "Ethiopia" => Ok(Locale::AmEt),
            "United Arab Emirates" => Ok(Locale::ArAe),
            "Bahrain" => Ok(Locale::ArBh),
            "Algeria" => Ok(Locale::ArDz),
            "Egypt" => Ok(Locale::ArEg),
            "Western Sahara" => Ok(Locale::ArEh),
            "Gaza Strip" => Ok(Locale::ArGz),
            "Iraq" => Ok(Locale::ArIq),
            "Jordan" => Ok(Locale::ArJo),
            "Kuwait" => Ok(Locale::ArKw),
            "Lebanon" => Ok(Locale::ArLb),
            "Libya" => Ok(Locale::ArLy),
            "Morocco" => Ok(Locale::ArMa),
            "Oman" => Ok(Locale::ArOm),
            "Qatar" => Ok(Locale::ArQa),
            "Saudi Arabia" => Ok(Locale::ArSa),
            "South Sudan" => Ok(Locale::ArSs),
            "Tunisia" => Ok(Locale::ArTn),
            "West Bank" => Ok(Locale::ArWb),
            "Yemen" => Ok(Locale::ArYe),
            "Belarus" => Ok(Locale::BeBy),
            "Bulgaria" => Ok(Locale::BgBg),
            "Bangladesh" => Ok(Locale::BnBd),
            "Česká republika" => Ok(Locale::CsCz),
            "Danmark" => Ok(Locale::DaDk),
            "Österreich" => Ok(Locale::DeAt),
            "Schweiz" => Ok(Locale::DeCh),
            "Deutschland" => Ok(Locale::DeDe),
            "Liechtenstein" => Ok(Locale::DeLi),
            "Ελλάδα" => Ok(Locale::ElGr),
            "Antigua and Barbuda" => Ok(Locale::EnAg),
            "Anguilla" => Ok(Locale::EnAi),
            "Netherlands Antilles" => Ok(Locale::EnAn),
            "Angola" => Ok(Locale::EnAo),
            "Antarctica" => Ok(Locale::EnAq),
            "American Samoa" => Ok(Locale::EnAs),
            "Australia" => Ok(Locale::EnAu),
            "Aruba" => Ok(Locale::EnAw),
            "Azerbaijan" => Ok(Locale::EnAz),
            "Bosnia and Herzegovina" => Ok(Locale::EnBa),
            "Barbados" => Ok(Locale::EnBb),
            "Burkina Faso" => Ok(Locale::EnBf),
            "Burundi" => Ok(Locale::EnBi),
            "Benin" => Ok(Locale::EnBj),
            "Saint Barthélemy" => Ok(Locale::EnBl),
            "Bermuda" => Ok(Locale::EnBm),
            "Bahamas, The" => Ok(Locale::EnBs),
            "Bhutan" => Ok(Locale::EnBt),
            "Botswana" => Ok(Locale::EnBw),
            "Belize" => Ok(Locale::EnBz),
            "Canada (English)" => Ok(Locale::EnCa),
            "Cocos (Keeling) Islands" => Ok(Locale::EnCc),
            "Central African Republic" => Ok(Locale::EnCf),
            "Cook Islands" => Ok(Locale::EnCk),
            "Cape Verde" => Ok(Locale::EnCv),
            "Christmas Island" => Ok(Locale::EnCx),
            "Cyprus" => Ok(Locale::EnCy),
            "Djibouti" => Ok(Locale::EnDj),
            "Eritrea" => Ok(Locale::EnEr),
            "Fiji Islands" => Ok(Locale::EnFj),
            "Falkland Islands (Islas Malvinas)" => Ok(Locale::EnFk),
            "Micronesia" => Ok(Locale::EnFm),
            "United Kingdom" => Ok(Locale::EnGb),
            "Grenada" => Ok(Locale::EnGd),
            "Channel Islands - Guernsey" => Ok(Locale::EnGg),
            "Ghana" => Ok(Locale::EnGh),
            "Gibraltar" => Ok(Locale::EnGi),
            "Gambia, The" => Ok(Locale::EnGm),
            "Guinea" => Ok(Locale::EnGn),
            "Equatorial Guinea" => Ok(Locale::EnGq),
            "S. Georgia and S. Sandwich Isls." => Ok(Locale::EnGs),
            "Guam" => Ok(Locale::EnGu),
            "Guinea-Bissau" => Ok(Locale::EnGw),
            "Guyana" => Ok(Locale::EnGy),
            "Hong Kong S.A.R. (English)" => Ok(Locale::EnHk),
            "Heard and McDonald Islands" => Ok(Locale::EnHm),
            "Ireland" => Ok(Locale::EnIe),
            "Isle of Man" => Ok(Locale::EnIm),
            "India" => Ok(Locale::EnIn),
            "British Indian Ocean Territory" => Ok(Locale::EnIo),
            "Channel Islands - Jersey" => Ok(Locale::EnJe),
            "Jamaica" => Ok(Locale::EnJm),
            "Kiribati" => Ok(Locale::EnKi),
            "St. Kitts and Nevis" => Ok(Locale::EnKn),
            "Cayman Islands" => Ok(Locale::EnKy),
            "Laos" => Ok(Locale::EnLa),
            "St. Lucia" => Ok(Locale::EnLc),
            "Liberia" => Ok(Locale::EnLr),
            "Lesotho" => Ok(Locale::EnLs),
            "Moldova" => Ok(Locale::EnMd),
            "Montenegro" => Ok(Locale::EnMe),
            "Marshall Islands" => Ok(Locale::EnMh),
            "Mali" => Ok(Locale::EnMl),
            "Myanmar" => Ok(Locale::EnMm),
            "Macau SAR" => Ok(Locale::EnMo),
            "Northern Mariana Islands" => Ok(Locale::EnMp),
            "Mauritania" => Ok(Locale::EnMr),
            "Montserrat" => Ok(Locale::EnMs),
            "Maldives" => Ok(Locale::EnMv),
            "Malawi" => Ok(Locale::EnMw),
            "Mozambique" => Ok(Locale::EnMz),
            "Namibia" => Ok(Locale::EnNa),
            "Niger" => Ok(Locale::EnNe),
            "Norfolk Island" => Ok(Locale::EnNf),
            "Nigeria" => Ok(Locale::EnNg),
            "Nauru" => Ok(Locale::EnNr),
            "Niue" => Ok(Locale::EnNu),
            "New Zealand" => Ok(Locale::EnNz),
            "Papua New Guinea" => Ok(Locale::EnPg),
            "Philippines" => Ok(Locale::EnPh),
            "Pitcairn Islands" => Ok(Locale::EnPn),
            "Palestinian Authority" => Ok(Locale::EnPs),
            "Palau" => Ok(Locale::EnPw),
            "Reunion" => Ok(Locale::EnRe),
            "Serbia" => Ok(Locale::EnRs),
            "Solomon Islands" => Ok(Locale::EnSb),
            "Seychelles" => Ok(Locale::EnSc),
            "Singapore" => Ok(Locale::EnSg),
            "St. Helena" => Ok(Locale::EnSh),
            "Sierra Leone" => Ok(Locale::EnSl),
            "San Marino" => Ok(Locale::EnSm),
            "Somalia" => Ok(Locale::EnSo),
            "Suriname" => Ok(Locale::EnSr),
            "Sao Tome and Principe" => Ok(Locale::EnSt),
            "Sint Maarten" => Ok(Locale::EnSx),
            "Swaziland" => Ok(Locale::EnSz),
            "Turks and Caicos Islands" => Ok(Locale::EnTc),
            "Chad" => Ok(Locale::EnTd),
            "Tajikistan" => Ok(Locale::EnTj),
            "Tokelau" => Ok(Locale::EnTk),
            "Timor-Leste" => Ok(Locale::EnTl),
            "Tonga" => Ok(Locale::EnTo),
            "Trinidad and Tobago" => Ok(Locale::EnTt),
            "Tuvalu" => Ok(Locale::EnTv),
            "Tanzania" => Ok(Locale::EnTz),
            "Uganda" => Ok(Locale::EnUg),
            "US Minor Outlying Islands" => Ok(Locale::EnUm),
            "United States" => Ok(Locale::EnUs),
            "Uzbekistan" => Ok(Locale::EnUz),
            "Vatican City" => Ok(Locale::EnVa),
            "St. Vincent and the Grenadines" => Ok(Locale::EnVc),
            "Virgin Islands, British" => Ok(Locale::EnVg),
            "Virgin Islands, U.S." => Ok(Locale::EnVi),
            "Vanuatu" => Ok(Locale::EnVu),
            "Samoa" => Ok(Locale::EnWs),
            "Sint Eustatius" => Ok(Locale::EnXe),
            "Saba" => Ok(Locale::EnXs),
            "South Africa" => Ok(Locale::EnZa),
            "Zambia" => Ok(Locale::EnZm),
            "Zimbabwe" => Ok(Locale::EnZw),
            "Argentina" => Ok(Locale::EsAr),
            "Bolivia" => Ok(Locale::EsBo),
            "Chile" => Ok(Locale::EsCl),
            "Colombia" => Ok(Locale::EsCo),
            "Costa Rica" => Ok(Locale::EsCr),
            "Dominica" => Ok(Locale::EsDm),
            "República Dominicana" => Ok(Locale::EsDo),
            "Ecuador" => Ok(Locale::EsEc),
            "España" => Ok(Locale::EsEs),
            "Guatemala" => Ok(Locale::EsGt),
            "Honduras" => Ok(Locale::EsHn),
            "México" => Ok(Locale::EsMx),
            "Nicaragua" => Ok(Locale::EsNi),
            "Panamá" => Ok(Locale::EsPa),
            "Peru" => Ok(Locale::EsPe),
            "Paraguay" => Ok(Locale::EsPy),
            "El Salvador" => Ok(Locale::EsSv),
            "Uruguay" => Ok(Locale::EsUy),
            "Venezuela" => Ok(Locale::EsVe),
            "Estonia" => Ok(Locale::EtEe),
            "Suomi" => Ok(Locale::FiFi),
            "Faroe Islands" => Ok(Locale::FoFo),
            "Andorra" => Ok(Locale::FrAd),
            "Belgique" => Ok(Locale::FrBe),
            "Canada (Français)" => Ok(Locale::FrCa),
            "Congo (DRC)" => Ok(Locale::FrCd),
            "Congo" => Ok(Locale::FrCg),
            "Suisse" => Ok(Locale::FrCh),
            "Côte d'Ivoire" => Ok(Locale::FrCi),
            "Cameroon" => Ok(Locale::FrCm),
            "France" => Ok(Locale::FrFr),
            "Gabon" => Ok(Locale::FrGa),
            "French Guiana" => Ok(Locale::FrGf),
            "Guadeloupe" => Ok(Locale::FrGp),
            "Haiti" => Ok(Locale::FrHt),
            "Comoros" => Ok(Locale::FrKm),
            "Monaco" => Ok(Locale::FrMc),
            "Saint Martin" => Ok(Locale::FrMf),
            "Madagascar" => Ok(Locale::FrMg),
            "Martinique" => Ok(Locale::FrMq),
            "Mauritius" => Ok(Locale::FrMu),
            "New Caledonia" => Ok(Locale::FrNc),
            "French Polynesia" => Ok(Locale::FrPf),
            "St. Pierre and Miquelon" => Ok(Locale::FrPm),
            "French Southern Territories" => Ok(Locale::FrTf),
            "Togo" => Ok(Locale::FrTg),
            "Wallis and Futuna" => Ok(Locale::FrWf),
            "Mayotte" => Ok(Locale::FrYt),
            "Israel" => Ok(Locale::HeIl),
            "Croatia" => Ok(Locale::HrHr),
            "Magyarország" => Ok(Locale::HuHu),
            "Armenia" => Ok(Locale::HyAm),
            "Indonesia" => Ok(Locale::IdId),
            "Iceland" => Ok(Locale::IsIs),
            "Italia" => Ok(Locale::ItIt),
            "日本 (Japan)" => Ok(Locale::JaJp),
            "Georgia" => Ok(Locale::KaGe),
            "Kazakhstan" => Ok(Locale::KkKz),
            "Greenland" => Ok(Locale::KlGl),
            "Cambodia" => Ok(Locale::KmKh),
            "대한민국 (Korea)" => Ok(Locale::KoKr),
            "Kyrgyzstan" => Ok(Locale::KyKg),
            "Luxembourg" => Ok(Locale::LbLu),
            "Lithuania" => Ok(Locale::LtLt),
            "Latvia" => Ok(Locale::LvLv),
            "Macedonia, Former Yugoslvaian Republic of" => Ok(Locale::MkMk),
            "Mongolia" => Ok(Locale::MnMn),
            "Brunei" => Ok(Locale::MsBn),
            "Malaysia" => Ok(Locale::MsMy),
            "Malta" => Ok(Locale::MtMt),
            "Bouvet Island" => Ok(Locale::NbBv),
            "Norge" => Ok(Locale::NbNo),
            "Svalbard" => Ok(Locale::NbSj),
            "Jan Mayen" => Ok(Locale::NbXj),
            "Nepal" => Ok(Locale::NeNp),
            "België" => Ok(Locale::NlBe),
            "Bonaire" => Ok(Locale::NlBq),
            "Curaçao" => Ok(Locale::NlCw),
            "Nederland" => Ok(Locale::NlNl),
            "Polska" => Ok(Locale::PlPl),
            "Afghanistan" => Ok(Locale::PsAf),
            "Brasil" => Ok(Locale::PtBr),
            "Portugal" => Ok(Locale::PtPt),
            "Romania" => Ok(Locale::RoRo),
            "Pоссия" => Ok(Locale::RuRu),
            "Rwanda" => Ok(Locale::RwRw),
            "Sri Lanka" => Ok(Locale::SiLk),
            "Slovakia" => Ok(Locale::SkSk),
            "Slovenia" => Ok(Locale::SlSi),
            "Albania" => Ok(Locale::SqAl),
            "Kosovo" => Ok(Locale::SqXk),
            "Aland Islands" => Ok(Locale::SvAx),
            "Sverige" => Ok(Locale::SvSe),
            "Kenya" => Ok(Locale::SwKe),
            "Thailand" => Ok(Locale::ThTh),
            "Turkmenistan" => Ok(Locale::TkTm),
            "Türkiye" => Ok(Locale::TrTr),
            "Ukraine" => Ok(Locale::UkUa),
            "Pakistan" => Ok(Locale::UrPk),
            "Vietnam" => Ok(Locale::ViVn),
            "Senegal" => Ok(Locale::WoSn),
            "中华人民共和国 (China)" => Ok(Locale::ZhCn),
            "Hong Kong S.A.R. (香港)" => Ok(Locale::ZhHk),
            "台灣 (Taiwan)" => Ok(Locale::ZhTw),
            _ => Err(format!("Invalid territory: {}", s).into()),
        }
    }
}
